# Generated by Django 4.2.4 on 2025-02-03 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(default='default_company.jpg', upload_to='companies/')),
                ('description', models.TextField(default='')),
                ('website', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='created_at',
        ),
        migrations.AddField(
            model_name='insurance',
            name='type',
            field=models.CharField(choices=[('LIFE', 'Life Insurance'), ('HEALTH', 'Health Insurance'), ('HOME', 'Home Insurance'), ('AUTO', 'Auto Insurance'), ('BUSINESS', 'Business Insurance')], default='LIFE', max_length=20),
        ),
        migrations.AlterField(
            model_name='agent',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='agent',
            name='profile_picture',
            field=models.ImageField(default='default_agent.jpg', upload_to='agents/'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='image',
            field=models.ImageField(default='default_insurance.jpg', upload_to='insurance/'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('features', models.TextField(default='')),
                ('price_range', models.CharField(default='Contact for pricing', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.insurancecompany')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='agent.insurance')),
            ],
        ),
    ]
