# Generated by Django 5.1.6 on 2025-04-14 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceplan',
            name='company',
        ),
        migrations.DeleteModel(
            name='InsuranceCompany',
        ),
    ]
