# Generated by Django 5.1.6 on 2025-04-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_remove_insuranceplan_company_delete_insurancecompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text="Font Awesome icon class (e.g., 'fa-shield-alt')", max_length=50)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers shown first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='insuranceplan',
            name='insurance',
        ),
        migrations.DeleteModel(
            name='Insurance',
        ),
        migrations.DeleteModel(
            name='InsurancePlan',
        ),
    ]
