# Generated by Django 5.1.6 on 2025-04-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_service_remove_insuranceplan_insurance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the service', null=True),
        ),
    ]
